// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package posts

import (
	"context"
)

type Querier interface {
	ListAll(ctx context.Context, db DBTX) ([]Post, error)
}

var _ Querier = (*Queries)(nil)
