#!/usr/bin/env bash

set -euo pipefail

# Fix code formatting.
mise tidy

# While all files are formatted, only files which were already staged are staged again.
# This is done to prevent accidental staging of intentionally unstaged files.
# Deleted files are filtered out as attempting to re-stage them will result in an error.
staged_files=($(git diff --name-only --cached --diff-filter=d))
git add -- "${staged_files[@]}"