// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package pets

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Pet struct {
	Id         int64       `db:"id"`
	Name       string      `db:"name"`
	CategoryId int64       `db:"category_id"`
	Status     pgtype.Text `db:"status"`
	ImageUrls  []string    `db:"image_urls"`
	CreatedAt  time.Time   `db:"created_at"`
	UpdatedAt  time.Time   `db:"updated_at"`
}
