// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pets.sql

package pets

import (
	"context"
)

const create = `-- name: Create :one
INSERT INTO public.pets (name, category_id, image_urls)
VALUES ($1, $2, $3)
RETURNING id, name, category_id, status, image_urls, created_at, updated_at
`

type CreateParams struct {
	Name       string   `db:"name"`
	CategoryId int64    `db:"category_id"`
	ImageUrls  []string `db:"image_urls"`
}

func (q *Queries) Create(ctx context.Context, db DBTX, arg CreateParams) (Pet, error) {
	row := db.QueryRow(ctx, create, arg.Name, arg.CategoryId, arg.ImageUrls)
	var i Pet
	err := row.Scan(
		&i.Id,
		&i.Name,
		&i.CategoryId,
		&i.Status,
		&i.ImageUrls,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
