run:
  timeout: 5m
  issues-exit-code: 10

output:
  show-stats: true

linters:
  enable:
    - wrapcheck
    - nilerr
    - nilnil
    - nonamedreturns
    - gocritic
    - depguard
    - errorlint
    - sloglint

linters-settings:
  depguard:
    rules:
      use_pkg_errors:
        files:
          - $all
        deny:
          - pkg: errors
            desc: "use github.com/pkg/errors instead of the standard errors package in order to have a stacktrace"

  sloglint:
    # Enforce using attributes only (overrides no-mixed-args, incompatible with kv-only).
    # https://github.com/go-simpler/sloglint?tab=readme-ov-file#attributes-only
    # Default: false
    attr-only: true

    # Enforce a single key naming convention.
    # Values: snake, kebab, camel, pascal
    # https://github.com/go-simpler/sloglint?tab=readme-ov-file#key-naming-convention
    # Default: ""
    key-naming-case: snake