version: "2"

run:
  timeout: 5m
  issues-exit-code: 10

output:
  show-stats: true

formatters:
  enable:
    - gci
    - gofmt # Although gofumpt covers all gofmt format rules, gofmt is still needed for pattern replacement which gofumpt doesn't support.
    - gofumpt

  settings:
    gci:
      sections:
        - standard
        - localmodule
        - default

      custom-order: true

    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'

        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'

linters:
  enable:
    - errorlint
    - gocritic
    - govet
    - importas
    - nilerr
    - nilnil
    - nonamedreturns
    - revive
    - sloglint
    - wrapcheck

  settings:
    errcheck:
      check-type-assertions: true
      exclude-functions:
        - (io.Closer).Close

    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow

    importas:
      # Do not allow unaliased imports of aliased packages.
      # Default: false
      no-unaliased: true

      # List of aliases
      # Default: []
      alias:
        - pkg: github.com/rhodeon/go-backend-template/cmd/api/errors
          alias: apierrors

        - pkg: github.com/rhodeon/go-backend-template/repositories/database/postgres/sqlcgen/(\w+)
          alias: db$1

      # Do not allow non-required aliases.
      # Default: false
      # It would be ideal to have this active, but currently enabling both no-unaliased and no-extra-aliases fails:
      # https://github.com/julz/importas/issues/15
      # no-extra-aliases: true

    revive:
      rules:
        - name: datarace

        - name: defer

        - name: empty-block

        - name: enforce-repeated-arg-type-style
          arguments:
            - "full"

        - name: enforce-map-style
          arguments:
            - "literal"

        - name: enforce-slice-style
          arguments:
            - "literal"

        - name: import-alias-naming
          arguments:
            - "^[a-z][a-z0-9]{0,}$"

        - name: import-shadowing

        - name: redundant-import-alias

        - name: time-equal

    sloglint:
      # Enforce using attributes only (overrides no-mixed-args, incompatible with kv-only).
      # https://github.com/go-simpler/sloglint?tab=readme-ov-file#attributes-only
      # Default: false
      attr-only: true

      # Enforce a single key naming convention.
      # Values: snake, kebab, camel, pascal
      # https://github.com/go-simpler/sloglint?tab=readme-ov-file#key-naming-convention
      # Default: ""
      key-naming-case: snake

      no-global: "all"

      msg-style: "capitalized"

      no-raw-keys: true

      static-msg: true

    wrapcheck:
      extra-ignore-sigs:
        - .UntypedError(
