#!/bin/bash
#MISE description="Start the API service"

containers="postgres redis aspire-dashboard otel-collector"

cleanup() {
    echo "Stopping containers..."
    docker compose down $containers
}

trap cleanup EXIT

echo "Starting containers..."
docker compose up --detach --remove-orphans $containers

echo "Starting API..."
echo "View API logs at http://localhost:18888"

# The API is redirected to a file to allow easier capture by the OTel filelog receiver.
cd ./cmd/api && go run . >api.log  2>&1
