#!/bin/bash
#MISE description="Run migrations. Use `mise migrations` to see all commands, and 'mise run migrations -- <args>' to pass arguments"

containers="postgres"

cleanup() {
    echo "Stopping containers..."
    docker compose down $containers
}

trap cleanup EXIT

echo "Starting containers..."
docker compose up --detach --remove-orphans $containers

echo "Starting migrations..."
cd ./cmd/migrations && go run . ${@}