// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package users

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	Id             int64       `db:"id"`
	Username       string      `db:"username"`
	FirstName      string      `db:"first_name"`
	LastName       string      `db:"last_name"`
	Email          string      `db:"email"`
	PhoneNumber    pgtype.Text `db:"phone_number"`
	HashedPassword string      `db:"hashed_password"`
	CreatedAt      time.Time   `db:"created_at"`
	UpdatedAt      time.Time   `db:"updated_at"`
}
