// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package users

import (
	"context"
)

type Querier interface {
	Create(ctx context.Context, db DBTX, arg CreateParams) (User, error)
	Delete(ctx context.Context, db DBTX, id int32) (User, error)
	GetById(ctx context.Context, db DBTX, id int32) (User, error)
	ListPosts(ctx context.Context, db DBTX) ([]Post, error)
	Update(ctx context.Context, db DBTX, arg UpdateParams) (User, error)
}

var _ Querier = (*Queries)(nil)
