// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: posts.sql

package posts

import (
	"context"
)

const listAll = `-- name: ListAll :many
SELECT id, content, user_id, created_at, updates_at
FROM posts
`

func (q *Queries) ListAll(ctx context.Context, db DBTX) ([]Post, error) {
	rows, err := db.Query(ctx, listAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Post{}
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.Id,
			&i.Content,
			&i.UserId,
			&i.CreatedAt,
			&i.UpdatesAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
