// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: pet_categories.sql

package petcategories

import (
	"context"
)

const getById = `-- name: GetById :one
SELECT id, name FROM public.pet_categories
WHERE id = $1
`

func (q *Queries) GetById(ctx context.Context, db DBTX, id int64) (PetCategory, error) {
	row := db.QueryRow(ctx, getById, id)
	var i PetCategory
	err := row.Scan(&i.Id, &i.Name)
	return i, err
}
